//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LBV6ForumApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LBV6ForumApp.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; style=&quot;height: 100%;&quot;&gt;
        ///    &lt;body style=&quot;padding:0; margin:0; height:100%; background-color: #f9f9f9; font-family: &apos;Helvetica Neue&apos;, Helvetica, Arial, sans-serif; font-size: 16px;&quot;&gt;
        ///		&lt;table id=&quot;background&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; width=&quot;100%&quot; height=&quot;100%&quot;&gt;
        ///			&lt;tr&gt;
        ///				&lt;td bgcolor=&quot;#f9f9f9&quot; style=&quot;padding-bottom: 200px;&quot; height=&quot;100%&quot; valign=&quot;top&quot;&gt;
        ///
        ///					&lt;table id=&quot;top&quot; cellspacing=&quot;0&quot; cellpadding=&quot;20&quot; border=&quot;0&quot; width=&quot;100 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _Master {
            get {
                return ResourceManager.GetString("_Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; style=&quot;height: 100%;&quot;&gt;
        ///    &lt;body style=&quot;padding:0; margin:0; height:100%; background-color: #f9f9f9; font-family: &apos;Helvetica Neue&apos;, Helvetica, Arial, sans-serif; font-size: 16px;&quot;&gt;
        ///		&lt;table id=&quot;background&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; width=&quot;100%&quot; height=&quot;100%&quot;&gt;
        ///			&lt;tr&gt;
        ///				&lt;td bgcolor=&quot;#f9f9f9&quot; style=&quot;padding-bottom: 200px;&quot; height=&quot;100%&quot; valign=&quot;top&quot;&gt;
        ///
        ///					&lt;table id=&quot;top&quot; cellspacing=&quot;0&quot; cellpadding=&quot;20&quot; border=&quot;0&quot; width=&quot;100 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _Master2 {
            get {
                return ResourceManager.GetString("_Master2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///	&lt;b&gt;{0}&lt;/b&gt;, we need to confirm your e-mail address. If you signed-up to londonbikers then please click the link below. If you didn&apos;t, you can safely ignore this email and nothing bad will happen.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///	Confirmation link:&lt;br /&gt;
        ///	&lt;a href=&quot;{1}&quot; target=&quot;_blank&quot; style=&quot;color: #fff; text-decoration: underline; font-weight: bold;&quot;&gt;{1}&lt;/a&gt;
        ///&lt;/p&gt;.
        /// </summary>
        internal static string EmailConfirmationRequiredHtml {
            get {
                return ResourceManager.GetString("EmailConfirmationRequiredHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, we need to confirm your e-mail address. If you signed-up to londonbikers then please click the link below. If you didn&apos;t, you can safely ignore this email and nothing bad will happen.
        ///
        ///Confirmation link:
        ///{1}
        ///
        ///
        ///https://londonbikers.com.
        /// </summary>
        internal static string EmailConfirmationRequiredText {
            get {
                return ResourceManager.GetString("EmailConfirmationRequiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///	{0}, someone&apos;s replied to a photo on a thread you&apos;re following:&lt;br /&gt;
        ///	&lt;b&gt;{1}&lt;/b&gt;
        ///&lt;/p&gt;
        ///&lt;div style=&quot;padding: 5px 20px 20px 20px; border-radius: 3px; background-color: #3dade1;&quot;&gt;
        ///	&lt;p&gt;									
        ///		&lt;b&gt;{2}&lt;/b&gt; wrote:&lt;br /&gt;
        ///		&lt;i&gt;&quot;{3}&quot;&lt;/i&gt;
        ///	&lt;/p&gt;
        ///
        ///	&lt;a href=&quot;{4}&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;{5}/os/{6}?maxwidth=200&amp;maxheight=200&quot; style=&quot;border-radius: 3px;vertical-align:middle;&quot; style=&quot;max-width:200px; max-height:200px;&quot; /&gt;&lt;/a&gt;
        ///
        ///&lt;/div&gt;
        ///&lt;p&gt;
        ///	See the whole thing at:&lt;br /&gt;
        ///	&lt;a href=&quot;{4}&quot; target=&quot;_blank&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewPhotoCommentHtml {
            get {
                return ResourceManager.GetString("NewPhotoCommentHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, someone&apos;s replied to a photo on a thread you&apos;re following:
        ///
        ///{1}
        ///
        ///{2} wrote:
        ///&quot;{3}&quot;
        ///
        ///See the whole thing at:
        ///{4}.
        /// </summary>
        internal static string NewPhotoCommentText {
            get {
                return ResourceManager.GetString("NewPhotoCommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///	{0}, there&apos;s been &lt;b&gt;{1}&lt;/b&gt; comments to a photo recently you&apos;re following on topic:&lt;br /&gt;
        ///	&lt;b&gt;{2}&lt;/b&gt;
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///	The latest comment was:
        ///&lt;/p&gt;
        ///&lt;div style=&quot;padding: 5px 20px 20px 20px; border-radius: 3px; background-color: #3dade1;&quot;&gt;
        ///	&lt;p&gt;									
        ///		&lt;b&gt;{3}&lt;/b&gt; wrote:&lt;br /&gt;
        ///		&lt;i&gt;&quot;{4}&quot;&lt;/i&gt;
        ///	&lt;/p&gt;
        ///	
        ///	&lt;a href=&quot;{5}&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;{6}/os/{7}?maxwidth=200&amp;maxheight=200&quot; style=&quot;border-radius: 3px;vertical-align:middle;&quot; style=&quot;max-width:200px; max-height:200px;&quot; /&gt;&lt;/a&gt;
        ///
        ///&lt;/div&gt;
        ///&lt;p&gt;
        ///	Se [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewPhotoCommentWithRollupsHtml {
            get {
                return ResourceManager.GetString("NewPhotoCommentWithRollupsHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, there&apos;s been {1} comments to a photo recently you&apos;re following on topic:
        ///{2}
        ///
        ///The latest comment was:
        ///							
        ///{3} wrote:
        ///&quot;{4}&quot;
        ///	
        ///See the whole thing at:
        ///{5}.
        /// </summary>
        internal static string NewPhotoCommentWithRollupsText {
            get {
                return ResourceManager.GetString("NewPhotoCommentWithRollupsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///	&lt;b&gt;{0}&lt;/b&gt;, someone&apos;s sent you a private message:
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///&lt;div style=&quot;padding: 5px 20px 5px 20px; border-radius: 3px; background-color: #40e2b6; color: #076149;&quot;&gt;
        ///	&lt;p&gt;		
        ///		&lt;b&gt;{1}&lt;/b&gt; wrote:&lt;br /&gt;
        ///		&lt;i&gt;&quot;{2}&quot;&lt;/i&gt;
        ///	&lt;/p&gt;		
        ///&lt;/div&gt;								
        ///&lt;p&gt;
        ///	See the whole message and any others in your &lt;b&gt;&lt;a href=&quot;{3}&quot; style=&quot;color: #1d6a55;&quot;&gt;Intercom&lt;/a&gt;&lt;/b&gt;.
        ///&lt;/p&gt;.
        /// </summary>
        internal static string NewPrivateMessageHtml {
            get {
                return ResourceManager.GetString("NewPrivateMessageHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, someone&apos;s sent you a private message:
        ///
        ///{1} wrote:
        ///&quot;{2}&quot;
        ///
        ///See the whole message and any others in your Intercom:
        ///{3}.
        /// </summary>
        internal static string NewPrivateMessageText {
            get {
                return ResourceManager.GetString("NewPrivateMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///	&lt;b&gt;{0}&lt;/b&gt;, you&apos;ve got a few unread private messages. The last one was:
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///&lt;div style=&quot;padding: 5px 20px 5px 20px; border-radius: 3px; background-color: #40e2b6; color: #076149;&quot;&gt;
        ///	&lt;p&gt;		
        ///		&lt;b&gt;{1}&lt;/b&gt; wrote:&lt;br /&gt;
        ///		&lt;i&gt;&quot;{2}&quot;&lt;/i&gt;
        ///	&lt;/p&gt;		
        ///&lt;/div&gt;								
        ///&lt;p&gt;
        ///	See the whole message and any others in your &lt;b&gt;&lt;a href=&quot;{3}&quot; style=&quot;color: #1d6a55;&quot;&gt;Intercom&lt;/a&gt;&lt;/b&gt;.
        ///&lt;/p&gt;.
        /// </summary>
        internal static string NewPrivateMessageWithRollupsHtml {
            get {
                return ResourceManager.GetString("NewPrivateMessageWithRollupsHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, you&apos;ve got a few unread private messages. The last one was:
        ///
        ///{1} wrote:
        ///&quot;{2}&quot;
        ///
        ///See the whole message and any others in your Intercom:
        ///{3}.
        /// </summary>
        internal static string NewPrivateMessageWithRollupsText {
            get {
                return ResourceManager.GetString("NewPrivateMessageWithRollupsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///	{0}, someone&apos;s posted in a forum you&apos;re following:&lt;br /&gt;
        ///	&lt;b&gt;{1} / {2}&lt;/b&gt;
        ///&lt;/p&gt;
        ///&lt;div style=&quot;padding: 5px 20px 5px 20px; border-radius: 3px; background-color: #3dade1;&quot;&gt;
        ///	&lt;p&gt;
        ///		In: {3}
        ///	&lt;/p&gt;
        ///	&lt;p&gt;		
        ///		&lt;b&gt;{4}&lt;/b&gt; wrote:&lt;br /&gt;
        ///		&lt;i&gt;&quot;{5}&quot;&lt;/i&gt;
        ///	&lt;/p&gt;		
        ///&lt;/div&gt;								
        ///&lt;p&gt;
        ///	See the whole post at:&lt;br /&gt;
        ///	&lt;a href=&quot;{6}&quot; target=&quot;_blank&quot; style=&quot;color: #fff; text-decoration: underline; font-weight: bold;&quot;&gt;{6}&lt;/a&gt;
        ///&lt;/p&gt;.
        /// </summary>
        internal static string NewTopicHtml {
            get {
                return ResourceManager.GetString("NewTopicHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///	{0}, someone&apos;s replied to a topic you&apos;re following:&lt;br /&gt;
        ///	&lt;b&gt;{1}&lt;/b&gt;
        ///&lt;/p&gt;
        ///&lt;div style=&quot;padding: 5px 20px 5px 20px; border-radius: 3px; background-color: #3dade1;&quot;&gt;
        ///	&lt;p&gt;									
        ///		&lt;b&gt;{2}&lt;/b&gt; wrote:&lt;br /&gt;
        ///		&lt;i&gt;&quot;{3}&quot;&lt;/i&gt;
        ///	&lt;/p&gt;		
        ///&lt;/div&gt;
        ///&lt;p&gt;
        ///	See the whole reply at:&lt;br /&gt;
        ///	&lt;a href=&quot;{4}&quot; target=&quot;_blank&quot; style=&quot;color: #fff; text-decoration: underline; font-weight: bold;&quot;&gt;{4}&lt;/a&gt;
        ///&lt;/p&gt;.
        /// </summary>
        internal static string NewTopicReplyHtml {
            get {
                return ResourceManager.GetString("NewTopicReplyHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, someone&apos;s replied to a topic you&apos;re following:
        ///
        ///{1}
        ///
        ///{2} wrote:
        ///&quot;{3}&quot;
        ///
        ///See the whole reply at:
        ///{4}.
        /// </summary>
        internal static string NewTopicReplyText {
            get {
                return ResourceManager.GetString("NewTopicReplyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///	{0}, someone&apos;s replied to a topic you&apos;re following:&lt;br /&gt;
        ///	&lt;b&gt;{1}&lt;/b&gt;
        ///&lt;/p&gt;
        ///&lt;div style=&quot;padding: 5px 20px 20px 20px; border-radius: 3px; background-color: #3dade1;&quot;&gt;
        ///	&lt;p&gt;									
        ///		&lt;b&gt;{2}&lt;/b&gt; wrote:&lt;br /&gt;
        ///		&lt;i&gt;&quot;{3}&quot;&lt;/i&gt;
        ///	&lt;/p&gt;
        ///
        ///	&lt;a href=&quot;{4}&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;{5}/os/{6}?width=100&amp;height=100&amp;mode=crop&quot; style=&quot;border-radius: 3px;vertical-align:middle;&quot; style=&quot;width:100px;height:100px;&quot; /&gt;&lt;/a&gt;
        ///
        ///&lt;/div&gt;
        ///&lt;p&gt;
        ///	See the whole reply at:&lt;br /&gt;
        ///	&lt;a href=&quot;{4}&quot; target=&quot;_blank&quot; style=&quot;color: #f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewTopicReplyWithPhotoHtml {
            get {
                return ResourceManager.GetString("NewTopicReplyWithPhotoHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///	{0}, someone&apos;s replied to a topic you&apos;re following:&lt;br /&gt;
        ///	&lt;b&gt;{1}&lt;/b&gt;
        ///&lt;/p&gt;
        ///&lt;div style=&quot;padding: 5px 20px 20px 20px; border-radius: 3px; background-color: #3dade1;&quot;&gt;
        ///	&lt;p&gt;									
        ///		&lt;b&gt;{2}&lt;/b&gt; wrote:&lt;br /&gt;
        ///		&lt;i&gt;&quot;{3}&quot;&lt;/i&gt;
        ///	&lt;/p&gt;
        ///
        ///	&lt;a href=&quot;{4}&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;{5}/os/{6}?width=100&amp;height=100&amp;mode=crop&quot; style=&quot;border-radius: 3px;vertical-align:middle;&quot; style=&quot;width:100px;height:100px;&quot; /&gt;&lt;/a&gt;
        ///
        ///	&lt;div style=&quot;width:100px;height:100px;display:inline-block;border-radius:3px;background-colo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewTopicReplyWithPhotosHtml {
            get {
                return ResourceManager.GetString("NewTopicReplyWithPhotosHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, someone&apos;s replied to a topic you&apos;re following:
        ///
        ///{1}
        ///
        ///{2} wrote:
        ///&quot;{3}&quot;
        ///
        ///See the whole reply at:
        ///{4}.
        /// </summary>
        internal static string NewTopicReplyWithPhotosText {
            get {
                return ResourceManager.GetString("NewTopicReplyWithPhotosText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///	{0}, someone&apos;s replied to a topic you&apos;re following:&lt;br /&gt;
        ///	&lt;b&gt;{1}&lt;/b&gt;
        ///&lt;/p&gt;
        ///&lt;div style=&quot;padding: 5px 20px 20px 20px; border-radius: 3px; background-color: #3dade1;&quot;&gt;
        ///	&lt;p&gt;									
        ///		&lt;b&gt;{2}&lt;/b&gt; posted:
        ///	&lt;/p&gt;
        ///
        ///	&lt;a href=&quot;{6}&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;{3}/os/{4}?width=100&amp;height=100&amp;mode=crop&quot; style=&quot;border-radius: 3px;vertical-align:middle;&quot; style=&quot;width:100px;height:100px;&quot; /&gt;&lt;/a&gt;
        ///
        ///	&lt;div style=&quot;width:100px;height:100px;display:inline-block;border-radius:3px;background-color:#35a0d1;color:#4cc6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewTopicReplyWithPhotosWithoutContentHtml {
            get {
                return ResourceManager.GetString("NewTopicReplyWithPhotosWithoutContentHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, someone&apos;s replied to a topic you&apos;re following:
        ///
        ///{1}
        ///
        ///{2} posted a photo.
        ///
        ///See the whole reply at:
        ///{6}.
        /// </summary>
        internal static string NewTopicReplyWithPhotosWithoutContentText {
            get {
                return ResourceManager.GetString("NewTopicReplyWithPhotosWithoutContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///	{0}, there&apos;s been &lt;b&gt;{1}&lt;/b&gt; replies to a topic you&apos;re following recently:&lt;br /&gt;
        ///	&lt;b&gt;{2}&lt;/b&gt;
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///	The latest reply is:
        ///&lt;/p&gt;
        ///&lt;div style=&quot;padding: 5px 20px 20px 20px; border-radius: 3px; background-color: #3dade1;&quot;&gt;
        ///	&lt;p&gt;									
        ///		&lt;b&gt;{3}&lt;/b&gt; posted:
        ///	&lt;/p&gt;
        ///	
        ///	&lt;a href=&quot;{7}&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;{4}/os/{5}?width=100&amp;height=100&amp;mode=crop&quot; style=&quot;border-radius: 3px;vertical-align:middle;&quot; style=&quot;width:100px;height:100px;&quot; /&gt;&lt;/a&gt;
        ///
        ///	&lt;div style=&quot;width:100px;height:100px;display:inline-bl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewTopicReplyWithPhotosWithoutContentWithRollupsHtml {
            get {
                return ResourceManager.GetString("NewTopicReplyWithPhotosWithoutContentWithRollupsHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, there&apos;s been &lt;b&gt;{1}&lt;/b&gt; replies to a topic you&apos;re following recently:
        ///
        ///{2}
        ///
        ///The last reply is:
        ///
        ///{3} posted a photo.
        ///
        ///See the whole reply at:
        ///{7}.
        /// </summary>
        internal static string NewTopicReplyWithPhotosWithoutContentWithRollupsText {
            get {
                return ResourceManager.GetString("NewTopicReplyWithPhotosWithoutContentWithRollupsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///	{0}, there&apos;s been &lt;b&gt;{1}&lt;/b&gt; replies to a topic you&apos;re following recently:&lt;br /&gt;
        ///	&lt;b&gt;{2}&lt;/b&gt;
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///	The latest reply is:
        ///&lt;/p&gt;
        ///&lt;div style=&quot;padding: 5px 20px 20px 20px; border-radius: 3px; background-color: #3dade1;&quot;&gt;
        ///	&lt;p&gt;									
        ///		&lt;b&gt;{3}&lt;/b&gt; wrote:&lt;br /&gt;
        ///		&lt;i&gt;&quot;{4}&quot;&lt;/i&gt;
        ///	&lt;/p&gt;
        ///	
        ///	&lt;a href=&quot;{5}&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;{6}/os/{7}?width=100&amp;height=100&amp;mode=crop&quot; style=&quot;border-radius: 3px;vertical-align:middle;&quot; style=&quot;width:100px;height:100px;&quot; /&gt;&lt;/a&gt;
        ///
        ///	&lt;div style=&quot;width:100px;height:10 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewTopicReplyWithPhotosWithRollupsHtml {
            get {
                return ResourceManager.GetString("NewTopicReplyWithPhotosWithRollupsHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, there&apos;s been &lt;b&gt;{1}&lt;/b&gt; replies to a topic you&apos;re following recently:
        ///
        ///{2}
        ///
        ///The last reply is:
        ///
        ///{3} wrote:
        ///&quot;{4}&quot;
        ///
        ///See the whole reply at:
        ///{5}.
        /// </summary>
        internal static string NewTopicReplyWithPhotosWithRollupsText {
            get {
                return ResourceManager.GetString("NewTopicReplyWithPhotosWithRollupsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, someone&apos;s replied to a topic you&apos;re following:
        ///
        ///{1}
        ///
        ///{2} wrote:
        ///&quot;{3}&quot;
        ///
        ///See the whole reply at:
        ///{4}.
        /// </summary>
        internal static string NewTopicReplyWithPhotoText {
            get {
                return ResourceManager.GetString("NewTopicReplyWithPhotoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///	{0}, someone&apos;s replied to a topic you&apos;re following:&lt;br /&gt;
        ///	&lt;b&gt;{1}&lt;/b&gt;
        ///&lt;/p&gt;
        ///&lt;div style=&quot;padding: 5px 20px 20px 20px; border-radius: 3px; background-color: #3dade1;&quot;&gt;
        ///	&lt;p&gt;									
        ///		&lt;b&gt;{2}&lt;/b&gt; posted:
        ///	&lt;/p&gt;
        ///
        ///	&lt;a href=&quot;{5}&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;{3}/os/{4}?width=100&amp;height=100&amp;mode=crop&quot; style=&quot;border-radius: 3px;vertical-align:middle;&quot; style=&quot;width:100px;height:100px;&quot; /&gt;&lt;/a&gt;
        ///
        ///&lt;/div&gt;
        ///&lt;p&gt;
        ///	See the whole reply at:&lt;br /&gt;
        ///	&lt;a href=&quot;{5}&quot; target=&quot;_blank&quot; style=&quot;color: #fff; text-decoration:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewTopicReplyWithPhotoWithoutContentHtml {
            get {
                return ResourceManager.GetString("NewTopicReplyWithPhotoWithoutContentHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, someone&apos;s replied to a topic you&apos;re following:
        ///
        ///{1}
        ///
        ///{2} posted a photo.
        ///
        ///See the whole reply at:
        ///{5}.
        /// </summary>
        internal static string NewTopicReplyWithPhotoWithoutContentText {
            get {
                return ResourceManager.GetString("NewTopicReplyWithPhotoWithoutContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///	{0}, there&apos;s been &lt;b&gt;{1}&lt;/b&gt; replies to a topic you&apos;re following recently:&lt;br /&gt;
        ///	&lt;b&gt;{2}&lt;/b&gt;
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///	The latest reply is:
        ///&lt;/p&gt;
        ///&lt;div style=&quot;padding: 5px 20px 20px 20px; border-radius: 3px; background-color: #3dade1;&quot;&gt;
        ///	&lt;p&gt;									
        ///		&lt;b&gt;{3}&lt;/b&gt; posted:
        ///	&lt;/p&gt;
        ///	
        ///	&lt;a href=&quot;{6}&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;{4}/os/{5}?width=100&amp;height=100&amp;mode=crop&quot; style=&quot;border-radius: 3px;vertical-align:middle;&quot; style=&quot;width:100px;height:100px;&quot; /&gt;&lt;/a&gt;
        ///
        ///&lt;/div&gt;
        ///&lt;p&gt;
        ///	See the whole reply at:&lt;br /&gt;
        ///	&lt;a href=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewTopicReplyWithPhotoWithoutContentWithRollupsHtml {
            get {
                return ResourceManager.GetString("NewTopicReplyWithPhotoWithoutContentWithRollupsHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, there&apos;s been &lt;b&gt;{1}&lt;/b&gt; replies to a topic you&apos;re following recently:
        ///
        ///{2}
        ///
        ///The last reply is:
        ///
        ///{3} posted a photo.
        ///
        ///See the whole reply at:
        ///{6}.
        /// </summary>
        internal static string NewTopicReplyWithPhotoWithoutContentWithRollupsText {
            get {
                return ResourceManager.GetString("NewTopicReplyWithPhotoWithoutContentWithRollupsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///	{0}, there&apos;s been &lt;b&gt;{1}&lt;/b&gt; replies to a topic you&apos;re following recently:&lt;br /&gt;
        ///	&lt;b&gt;{2}&lt;/b&gt;
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///	The latest reply is:
        ///&lt;/p&gt;
        ///&lt;div style=&quot;padding: 5px 20px 20px 20px; border-radius: 3px; background-color: #3dade1;&quot;&gt;
        ///	&lt;p&gt;									
        ///		&lt;b&gt;{3}&lt;/b&gt; wrote:&lt;br /&gt;
        ///		&lt;i&gt;&quot;{4}&quot;&lt;/i&gt;
        ///	&lt;/p&gt;
        ///	
        ///	&lt;a href=&quot;{5}&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;{6}/os/{7}?width=100&amp;height=100&amp;mode=crop&quot; style=&quot;border-radius: 3px;vertical-align:middle;&quot; style=&quot;width:100px;height:100px;&quot; /&gt;&lt;/a&gt;
        ///
        ///&lt;/div&gt;
        ///&lt;p&gt;
        ///	See the whole reply  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewTopicReplyWithPhotoWithRollupsHtml {
            get {
                return ResourceManager.GetString("NewTopicReplyWithPhotoWithRollupsHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, there&apos;s been &lt;b&gt;{1}&lt;/b&gt; replies to a topic you&apos;re following recently:
        ///
        ///{2}
        ///
        ///The last reply is:
        ///
        ///{3} wrote:
        ///&quot;{4}&quot;
        ///
        ///See the whole reply at:
        ///{5}.
        /// </summary>
        internal static string NewTopicReplyWithPhotoWithRollupsText {
            get {
                return ResourceManager.GetString("NewTopicReplyWithPhotoWithRollupsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///	{0}, there&apos;s been &lt;b&gt;{1}&lt;/b&gt; replies to a topic you&apos;re following recently:&lt;br /&gt;
        ///	&lt;b&gt;{2}&lt;/b&gt;
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///	The latest reply is:
        ///&lt;/p&gt;
        ///&lt;div style=&quot;padding: 5px 20px 5px 20px; border-radius: 3px; background-color: #3dade1;&quot;&gt;
        ///	&lt;p&gt;									
        ///		&lt;b&gt;{3}&lt;/b&gt; wrote:&lt;br /&gt;
        ///		&lt;i&gt;&quot;{4}&quot;&lt;/i&gt;
        ///	&lt;/p&gt;		
        ///&lt;/div&gt;
        ///&lt;p&gt;
        ///	See the whole reply at:&lt;br /&gt;
        ///	&lt;a href=&quot;{5}&quot; style=&quot;color: #21566f;&quot;&gt;{5}&lt;/a&gt;
        ///&lt;/p&gt;.
        /// </summary>
        internal static string NewTopicReplyWithRollupsHtml {
            get {
                return ResourceManager.GetString("NewTopicReplyWithRollupsHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, there&apos;s been &lt;b&gt;{1}&lt;/b&gt; replies to a topic you&apos;re following recently:
        ///
        ///{2}
        ///
        ///The last reply is:
        ///
        ///{3} wrote:
        ///&quot;{4}&quot;
        ///
        ///See the whole reply at:
        ///{5}.
        /// </summary>
        internal static string NewTopicReplyWithRollupsText {
            get {
                return ResourceManager.GetString("NewTopicReplyWithRollupsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, someone&apos;s posted in a forum you&apos;re following:
        ///
        ///{1} / {2}
        ///
        ///In: {3}
        ///
        ///{4} wrote:
        ///&quot;{5}&quot;
        ///
        ///See the whole post at:
        ///{6}.
        /// </summary>
        internal static string NewTopicText {
            get {
                return ResourceManager.GetString("NewTopicText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///	{0}, someone&apos;s posted in a forum you&apos;re following:&lt;br /&gt;
        ///	&lt;b&gt;{1} / {2}&lt;/b&gt;
        ///&lt;/p&gt;
        ///&lt;div style=&quot;padding: 5px 20px 20px 20px; border-radius: 3px; background-color: #3dade1;&quot;&gt;
        ///	&lt;p&gt;
        ///		In: {3}
        ///	&lt;/p&gt;
        ///	&lt;p&gt;		
        ///		&lt;b&gt;{4}&lt;/b&gt; wrote:&lt;br /&gt;
        ///		&lt;i&gt;&quot;{5}&quot;&lt;/i&gt;
        ///	&lt;/p&gt;
        ///
        ///	&lt;a href=&quot;{6}&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;{7}/os/{8}?width=100&amp;height=100&amp;mode=crop&quot; style=&quot;border-radius: 3px;vertical-align:middle;&quot; style=&quot;width:100px;height:100px;&quot; /&gt;&lt;/a&gt;
        ///
        ///&lt;/div&gt;								
        ///&lt;p&gt;
        ///	See the whole post at:&lt;br /&gt;
        ///	&lt;a href=&quot;{6}&quot; tar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewTopicWithPhotoHtml {
            get {
                return ResourceManager.GetString("NewTopicWithPhotoHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///	{0}, someone&apos;s posted in a forum you&apos;re following:&lt;br /&gt;
        ///	&lt;b&gt;{1} / {2}&lt;/b&gt;
        ///&lt;/p&gt;
        ///&lt;div style=&quot;padding: 5px 20px 20px 20px; border-radius: 3px; background-color: #3dade1;&quot;&gt;
        ///	&lt;p&gt;
        ///		In: {3}
        ///	&lt;/p&gt;
        ///	&lt;p&gt;		
        ///		&lt;b&gt;{4}&lt;/b&gt; wrote:&lt;br /&gt;
        ///		&lt;i&gt;&quot;{5}&quot;&lt;/i&gt;
        ///	&lt;/p&gt;
        ///
        ///	&lt;a href=&quot;{6}&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;{7}/os/{8}?width=100&amp;height=100&amp;mode=crop&quot; style=&quot;border-radius: 3px;vertical-align:middle;&quot; style=&quot;width:100px;height:100px;&quot; /&gt;&lt;/a&gt;
        ///										
        ///	&lt;div style=&quot;width:100px;height:100px;display:inline-block;b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewTopicWithPhotosHtml {
            get {
                return ResourceManager.GetString("NewTopicWithPhotosHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, someone&apos;s posted in a forum you&apos;re following:
        ///
        ///{1} / {2}
        ///
        ///In: {3}
        ///
        ///{4} wrote:
        ///&quot;{5}&quot;
        ///
        ///See the whole post at:
        ///{6}.
        /// </summary>
        internal static string NewTopicWithPhotosText {
            get {
                return ResourceManager.GetString("NewTopicWithPhotosText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///	{0}, someone&apos;s posted in a forum you&apos;re following:&lt;br /&gt;
        ///	&lt;b&gt;{1} / {2}&lt;/b&gt;
        ///&lt;/p&gt;
        ///&lt;div style=&quot;padding: 5px 20px 20px 20px; border-radius: 3px; background-color: #3dade1;&quot;&gt;
        ///	&lt;p&gt;
        ///		In: {3}
        ///	&lt;/p&gt;
        ///	&lt;p&gt;		
        ///		&lt;b&gt;{4}&lt;/b&gt; posted:
        ///	&lt;/p&gt;
        ///
        ///	&lt;a href=&quot;{8}&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;{5}/os/{6}?width=100&amp;height=100&amp;mode=crop&quot; style=&quot;border-radius: 3px;vertical-align:middle;&quot; style=&quot;width:100px;height:100px;&quot; /&gt;&lt;/a&gt;
        ///										
        ///	&lt;div style=&quot;width:100px;height:100px;display:inline-block;border-radius:3px;back [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewTopicWithPhotosWithoutContentHtml {
            get {
                return ResourceManager.GetString("NewTopicWithPhotosWithoutContentHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, someone&apos;s posted in a forum you&apos;re following:
        ///
        ///{1} / {2}
        ///
        ///In: {3}
        ///
        ///{4} posted a photo.
        ///
        ///See the whole post at:
        ///{8}.
        /// </summary>
        internal static string NewTopicWithPhotosWithoutContentText {
            get {
                return ResourceManager.GetString("NewTopicWithPhotosWithoutContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///	{0}, there&apos;s been &lt;b&gt;{1}&lt;/b&gt; new posts in a forum you&apos;re following since we last notified you:&lt;br /&gt;
        ///	&lt;b&gt;{2} / {3}&lt;/b&gt;
        ///&lt;/p&gt;
        ///&lt;div style=&quot;padding: 5px 20px 20px 20px; border-radius: 3px; background-color: #3dade1;&quot;&gt;
        ///	&lt;p&gt;
        ///		The last post was: {4}
        ///	&lt;/p&gt;
        ///	&lt;p&gt;		
        ///		&lt;b&gt;{5}&lt;/b&gt; posted:
        ///	&lt;/p&gt;
        ///
        ///	&lt;a href=&quot;{9}&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;{6}/os/{7}?width=100&amp;height=100&amp;mode=crop&quot; style=&quot;border-radius: 3px;vertical-align:middle;&quot; style=&quot;width:100px;height:100px;&quot; /&gt;&lt;/a&gt;
        ///										
        ///	&lt;div style=&quot;width:100 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewTopicWithPhotosWithoutContentWithRollupsHtml {
            get {
                return ResourceManager.GetString("NewTopicWithPhotosWithoutContentWithRollupsHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, there&apos;s been {1} new posts in a forum you&apos;re following since we last notified you:
        ///
        ///{2} / {3}
        ///
        ///The last post was: {4}
        ///
        ///{5} posted a photo.
        ///
        ///See the whole post at:
        ///{9}.
        /// </summary>
        internal static string NewTopicWithPhotosWithoutContentWithRollupsText {
            get {
                return ResourceManager.GetString("NewTopicWithPhotosWithoutContentWithRollupsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///	{0}, there&apos;s been &lt;b&gt;{1}&lt;/b&gt; new posts in a forum you&apos;re following since we last notified you:&lt;br /&gt;
        ///	&lt;b&gt;{2} / {3}&lt;/b&gt;
        ///&lt;/p&gt;
        ///&lt;div style=&quot;padding: 5px 20px 20px 20px; border-radius: 3px; background-color: #3dade1;&quot;&gt;
        ///	&lt;p&gt;
        ///		The last post was: {4}
        ///	&lt;/p&gt;
        ///	&lt;p&gt;		
        ///		&lt;b&gt;{5}&lt;/b&gt; wrote:&lt;br /&gt;
        ///		&lt;i&gt;&quot;{6}&quot;&lt;/i&gt;
        ///	&lt;/p&gt;
        ///
        ///	&lt;a href=&quot;{7}&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;{8}/os/{9}?width=100&amp;height=100&amp;mode=crop&quot; style=&quot;border-radius: 3px;vertical-align:middle;&quot; style=&quot;width:100px;height:100px;&quot; /&gt;&lt;/a&gt;
        ///										
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewTopicWithPhotosWithRollupsHtml {
            get {
                return ResourceManager.GetString("NewTopicWithPhotosWithRollupsHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, there&apos;s been {1} new posts in a forum you&apos;re following since we last notified you:
        ///
        ///{2}/ {3}
        ///
        ///The last post was: {4}
        ///
        ///{5} wrote:
        ///&quot;{6}&quot;
        ///
        ///See the whole post at:
        ///{7}.
        /// </summary>
        internal static string NewTopicWithPhotosWithRollupsText {
            get {
                return ResourceManager.GetString("NewTopicWithPhotosWithRollupsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, someone&apos;s posted in a forum you&apos;re following:
        ///
        ///{1} / {2}
        ///
        ///In: {3}
        ///
        ///{4} wrote:
        ///&quot;{5}&quot;
        ///
        ///See the whole post at:
        ///{6}.
        /// </summary>
        internal static string NewTopicWithPhotoText {
            get {
                return ResourceManager.GetString("NewTopicWithPhotoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///	{0}, someone&apos;s posted in a forum you&apos;re following:&lt;br /&gt;
        ///	&lt;b&gt;{1} / {2}&lt;/b&gt;
        ///&lt;/p&gt;
        ///&lt;div style=&quot;padding: 5px 20px 20px 20px; border-radius: 3px; background-color: #3dade1;&quot;&gt;
        ///	&lt;p&gt;
        ///		In: {3}
        ///	&lt;/p&gt;
        ///	&lt;p&gt;		
        ///		&lt;b&gt;{4}&lt;/b&gt; posted:
        ///	&lt;/p&gt;
        ///
        ///	&lt;a href=&quot;{7}&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;{5}/os/{6}?width=100&amp;height=100&amp;mode=crop&quot; style=&quot;border-radius: 3px;vertical-align:middle;&quot; style=&quot;width:100px;height:100px;&quot; /&gt;&lt;/a&gt;
        ///
        ///&lt;/div&gt;								
        ///&lt;p&gt;
        ///	See the whole post at:&lt;br /&gt;
        ///	&lt;a href=&quot;{7}&quot; target=&quot;_blank&quot; style=&quot;c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewTopicWithPhotoWithoutContentHtml {
            get {
                return ResourceManager.GetString("NewTopicWithPhotoWithoutContentHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, someone&apos;s posted in a forum you&apos;re following:
        ///
        ///{1} / {2}
        ///
        ///In: {3}
        ///
        ///{4} posted a photo.
        ///
        ///See the whole post at:
        ///{7}.
        /// </summary>
        internal static string NewTopicWithPhotoWithoutContentText {
            get {
                return ResourceManager.GetString("NewTopicWithPhotoWithoutContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///	{0}, there&apos;s been &lt;b&gt;{1}&lt;/b&gt; new posts in a forum you&apos;re following since we last notified you:&lt;br /&gt;
        ///	&lt;b&gt;{2} / {3}&lt;/b&gt;
        ///&lt;/p&gt;
        ///&lt;div style=&quot;padding: 5px 20px 20px 20px; border-radius: 3px; background-color: #3dade1;&quot;&gt;
        ///	&lt;p&gt;
        ///		The last post was: {4}
        ///	&lt;/p&gt;
        ///	&lt;p&gt;		
        ///		&lt;b&gt;{5}&lt;/b&gt; posted:&lt;br /&gt;
        ///	&lt;/p&gt;
        ///
        ///	&lt;a href=&quot;{8}&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;{6}/os/{7}?width=100&amp;height=100&amp;mode=crop&quot; style=&quot;border-radius: 3px;vertical-align:middle;&quot; style=&quot;width:100px;height:100px;&quot; /&gt;&lt;/a&gt;
        ///
        ///&lt;/div&gt;
        ///&lt;p&gt;
        ///	See the whol [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewTopicWithPhotoWithoutContentWithRollupsHtml {
            get {
                return ResourceManager.GetString("NewTopicWithPhotoWithoutContentWithRollupsHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, there&apos;s been {1} new posts in a forum you&apos;re following since we last notified you:
        ///
        ///{2} / {3}
        ///
        ///The last post was: {4}
        ///
        ///{5} posted a photo.
        ///
        ///See the whole post at:
        ///{8}.
        /// </summary>
        internal static string NewTopicWithPhotoWithoutContentWithRollupsText {
            get {
                return ResourceManager.GetString("NewTopicWithPhotoWithoutContentWithRollupsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///	{0}, there&apos;s been &lt;b&gt;{1}&lt;/b&gt; new posts in a forum you&apos;re following since we last notified you:&lt;br /&gt;
        ///	&lt;b&gt;{2} / {3}&lt;/b&gt;
        ///&lt;/p&gt;
        ///&lt;div style=&quot;padding: 5px 20px 20px 20px; border-radius: 3px; background-color: #3dade1;&quot;&gt;
        ///	&lt;p&gt;
        ///		The last post was: {4}
        ///	&lt;/p&gt;
        ///	&lt;p&gt;		
        ///		&lt;b&gt;{5}&lt;/b&gt; wrote:&lt;br /&gt;
        ///		&lt;i&gt;&quot;{6}&quot;&lt;/i&gt;
        ///	&lt;/p&gt;
        ///
        ///	&lt;a href=&quot;{7}&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;{8}/os/{9}?width=100&amp;height=100&amp;mode=crop&quot; style=&quot;border-radius: 3px;vertical-align:middle;&quot; style=&quot;width:100px;height:100px;&quot; /&gt;&lt;/a&gt;
        ///
        ///&lt;/div&gt;
        ///&lt;p&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewTopicWithPhotoWithRollupsHtml {
            get {
                return ResourceManager.GetString("NewTopicWithPhotoWithRollupsHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, there&apos;s been {1} new posts in a forum you&apos;re following since we last notified you:
        ///
        ///{2}/ {3}
        ///
        ///The last post was: {4}
        ///
        ///{5} wrote:
        ///&quot;{6}&quot;
        ///
        ///See the whole post at:
        ///{7}.
        /// </summary>
        internal static string NewTopicWithPhotoWithRollupsText {
            get {
                return ResourceManager.GetString("NewTopicWithPhotoWithRollupsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///	{0}, there&apos;s been &lt;b&gt;{1}&lt;/b&gt; new posts in a forum you&apos;re following since we last notified you:&lt;br /&gt;
        ///	&lt;b&gt;{2} / {3}&lt;/b&gt;
        ///&lt;/p&gt;
        ///&lt;div style=&quot;padding: 5px 20px 5px 20px; border-radius: 3px; background-color: #3dade1;&quot;&gt;
        ///	&lt;p&gt;
        ///		The last post was: {4}
        ///	&lt;/p&gt;
        ///	&lt;p&gt;		
        ///		&lt;b&gt;{5}&lt;/b&gt; wrote:&lt;br /&gt;
        ///		&lt;i&gt;&quot;{6}&quot;&lt;/i&gt;
        ///	&lt;/p&gt;		
        ///&lt;/div&gt;
        ///&lt;p&gt;
        ///	See the whole post at:&lt;br /&gt;
        ///	&lt;a href=&quot;{7}&quot; target=&quot;_blank&quot; style=&quot;color: #fff; text-decoration: underline; font-weight: bold;&quot;&gt;{7}&lt;/a&gt;
        ///&lt;/p&gt;.
        /// </summary>
        internal static string NewTopicWithRollupsHtml {
            get {
                return ResourceManager.GetString("NewTopicWithRollupsHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, there&apos;s been {1} new posts in a forum you&apos;re following since we last notified you:
        ///
        ///{2}/ {3}
        ///
        ///The last post was: {4}
        ///
        ///{5} wrote:
        ///&quot;{6}&quot;
        ///
        ///See the whole post at:
        ///{7}.
        /// </summary>
        internal static string NewTopicWithRollupsText {
            get {
                return ResourceManager.GetString("NewTopicWithRollupsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///	&lt;b&gt;{0}&lt;/b&gt;, someone, hopefully you, has asked to reset the password of your account. If this was you then please follow the link below to reset your password. If it wasn&apos;t you, please ignore this email and your account will remain secure and your password unchanged.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///	Reset password link:&lt;br /&gt;
        ///	&lt;a href=&quot;{1}&quot; target=&quot;_blank&quot; style=&quot;color: #fff; text-decoration: underline; font-weight: bold;&quot;&gt;{1}&lt;/a&gt;
        ///&lt;/p&gt;.
        /// </summary>
        internal static string PasswordResetLinkHtml {
            get {
                return ResourceManager.GetString("PasswordResetLinkHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, someone, hopefully you, has asked to reset the password of your account. If this was you then please follow the link below to reset your password. If it wasn&apos;t you, please ignore this email and your account will remain secure and your password unchanged.
        ///
        ///Reset password link:
        ///{1}
        ///
        ///
        ///https://londonbikers.com.
        /// </summary>
        internal static string PasswordResetLinkText {
            get {
                return ResourceManager.GetString("PasswordResetLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///	&lt;b&gt;{0}&lt;/b&gt;, just a headsup; we&apos;ve had to moderate one of your posts. See below for details:
        ///&lt;/p&gt;
        ///&lt;div style=&quot;padding: 5px 20px 5px 20px; border-radius: 3px; background-color: #3dade1;&quot;&gt;
        ///	&lt;table cellspacing=&quot;0&quot; cellpadding=&quot;20&quot; border=&quot;0&quot; width=&quot;100%&quot;&gt;
        ///		&lt;tr&gt;
        ///			&lt;td&gt;
        ///
        ///				&lt;table width=&quot;100%&quot; cellpadding=&quot;2&quot; cellspacing=&quot;0&quot;&gt;
        ///					&lt;tr&gt;
        ///						&lt;td width=&quot;120&quot;&gt;&lt;b&gt;Post:&lt;/b&gt;&lt;/td&gt;
        ///						&lt;td&gt;&lt;a href=&quot;{1}&quot; target=&quot;_blank&quot; style=&quot;color: #fff; text-decoration: underline; font-weight: bold;&quot;&gt;{2}&lt;/a&gt;&lt;/td&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PostModeratedNotificationHtml {
            get {
                return ResourceManager.GetString("PostModeratedNotificationHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, just a headsup; we&apos;ve had to moderate one of your posts. See below for details:
        ///
        ///Post: {2} &lt;{1}&gt;
        ///Action taken: {3}
        ///Reason: &quot;{4}&quot;
        ///
        ///No action is required from you.
        ///
        ///
        ///https://londonbikers.com.
        /// </summary>
        internal static string PostModeratedNotificationText {
            get {
                return ResourceManager.GetString("PostModeratedNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p style=&quot;font-size:1.3em;&quot;&gt;
        ///	&lt;b&gt;{0}&lt;/b&gt;, thanks for joining!
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///	We need to confirm your email address. Please click the link below to confirm that it was you that wanted to join londonbikers.com
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///	&lt;a href=&quot;{1}&quot; target=&quot;_blank&quot; style=&quot;color: #fff; text-decoration: underline; font-weight: bold;&quot;&gt;Click here to confirm your email address and join the community!&lt;/a&gt;
        ///&lt;/p&gt;.
        /// </summary>
        internal static string RegistrationEmailConfirmationRequiredHtml {
            get {
                return ResourceManager.GetString("RegistrationEmailConfirmationRequiredHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, thanks for registering!
        ///
        ///We need to confirm your email address. Please click the link below to confirm that it was you that wanted to join londonbikers.com
        ///
        ///Confirmation link:
        ///{1}
        ///
        ///
        ///https://londonbikers.com.
        /// </summary>
        internal static string RegistrationEmailConfirmationRequiredText {
            get {
                return ResourceManager.GetString("RegistrationEmailConfirmationRequiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p style=&quot;font-size:1.3em;&quot;&gt;
        ///	Welcome &lt;b&gt;{0}&lt;/b&gt;!
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///	You&apos;ve joined the biggest and best community for bikers in and around London. To get the most out of being a member we&apos;ve got some suggestions that might help you:
        ///&lt;/p&gt;
        ///								
        ///&lt;div style=&quot;padding: 5px 20px 5px 20px; border-radius: 3px; background-color: #3dade1;&quot;&gt;
        ///								
        ///	&lt;p&gt;&lt;b&gt;Introduce yourself&lt;/b&gt;&lt;/p&gt;
        ///	&lt;p&gt;Say hi and let us know what you&apos;re riding in our &lt;a href=&quot;https://londonbikers.com/forums/5/newbies&quot; target=&quot;_blank&quot; style=&quot;colo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WelcomeHtml {
            get {
                return ResourceManager.GetString("WelcomeHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome {0}!
        ///
        ///You&apos;ve joined the biggest and best community for bikers in and around London. To get the most out of being a member we&apos;ve got some suggestions that might help you:
        ///
        ///								
        ///- Introduce yourself
        ///Say hi and let us know what you&apos;re riding in our Newbies Forum (https://londonbikers.com/forums/5/newbies).
        ///									
        ///- Come to one of our newbie meets
        ///Posting in the newbie forum is a great way to have everyone see you&apos;ve arrived. We also host a monthly newbie night at the famous Ace Cafe on  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
    }
}
