// <auto-generated />
namespace LBV6ForumApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Fixedpostuseridtype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fixedpostuseridtype));
        
        string IMigrationMetadata.Id
        {
            get { return "201410200854132_Fixed post userid type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
