// <auto-generated />
namespace LBV6ForumApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FixReadByUserId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixReadByUserId));
        
        string IMigrationMetadata.Id
        {
            get { return "201602280214226_FixReadByUserId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
